site_name: CoreProtect Documentation
theme: readthedocs
repo_url: https://github.com/TF-Minecraft/CoreProtect
edit_uri: https://github.com/TF-Minecraft/Docs/edit/main/projects/CoreProtect/docs/
docs_dir: 'docs'
extra_css:
     - css/extra.css